name: Deploy

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Deploy SAM app to ECR
      uses: govuk-one-login/devplatform-upload-action-ecr@1.2.1
      with:
        artifact-bucket-name: ${{ secrets.ARTIFACT_SOURCE_BUCKET_NAME }}
        template-file: template.yaml
        role-to-assume-arn: ${{ secrets.GH_ACTIONS_ROLE_ARN }}
        ecr-repo-name: ${{ secrets.ECR_REPOSITORY }}